server:
  port: 8081

spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234


mybatis-plus:
  global-config:
    db-config:
      #id类型。
      id-type: AUTO # id改为自增。默认为ASSIGN_ID

